## Imports

In [1]:
import pandas as pd 
import numpy as np 

## Load the Data

In [2]:
data = pd.read_csv('Absenteeism_preprocessed.csv')
data.head(5)

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Create Targets

In [3]:
Targets = np.where(data['Absenteeism Time in Hours'] > data['Absenteeism Time in Hours'].median() , 1 , 0)
Targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [4]:
data['Excessive Absenteeism '] = Targets

In [5]:
data.head(5) 

Reason_1  Reason_2  Reason_3  Reason_4  Month  Day of the Week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism   
0                       1  
1                       0  
2                       0  
3                       1  
4                       0

In [6]:
#46% are ones and 54% are zeros
Targets.sum() / Targets.shape[0]

0.45571428571428574

### Checkpoint 1

In [7]:
data_with_targets = data.drop(['Absenteeism Time in Hours', 'Day of the Week', 
                              'Daily Work Load Average', 'Distance to Work'], axis=1)

In [8]:
data_with_targets is data

False

In [9]:
data_with_targets.head(5)

Reason_1  Reason_2  Reason_3  Reason_4  Month  Transportation Expense  Age  \
0         0         0         0         1      7                     289   33   
1         0         0         0         0      7                     118   50   
2         0         0         0         1      7                     179   38   
3         1         0         0         0      7                     279   39   
4         0         0         0         1      7                     289   33   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism   
0               30          0         2     1                       1  
1               31          0         1     0                       0  
2               31          0         0     0                       0  
3               24          0         2     0                       1  
4               30          0         2     1                       0

### Select the Inputs for the Regression

In [10]:
data_with_targets.shape

(700, 12)

In [11]:
#Removed the Target 
unscaled_inputs = data_with_targets.iloc[: ,:-1]

In [12]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month  Transportation Expense  \
0           0         0         0         1      7                     289   
1           0         0         0         0      7                     118   
2           0         0         0         1      7                     179   
3           1         0         0         0      7                     279   
4           0         0         0         1      7                     289   
..        ...       ...       ...       ...    ...                     ...   
695         1         0         0         0      5                     179   
696         1         0         0         0      5                     225   
697         1         0         0         0      5                     330   
698         0         0         0         1      5                     235   
699         0         0         0         1      5                     291   

     Age  Body Mass Index  Education  Children  Pets  
0     33               30          0         2     1  
1     50               31          0         1     0  
2     38               31          0         0     0  
3     39               24          0         2     0  
4     33               30          0         2     1  
..   ...              ...        ...       ...   ...  
695   40               22          1         2     0  
696   28               24          0         1     2  
697   28               25          1         0     0  
698   32               25          1         0     0  
699   40               25          0         1     1  

[700 rows x 11 columns]

### Stantardize the data

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
#we used a CustomScaler so we dont stantardize the Dummies 

# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler()
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [15]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [16]:
#columns_to_scale = ['Month','Day of the Week', 'Transportation Expense', 'Distance to Work',
 #      'Age', 'Daily Work Load Average', 'Body Mass Index',
  #     'Children', 'Pets']

In [17]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [18]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [19]:
Absenteeism_scaler = CustomScaler(columns_to_scale)

In [20]:
Absenteeism_scaler.fit(unscaled_inputs)

C:\Users\Abdallah\miniconda3\Lib\site-packages\numpy\core\fromnumeric.py:3745: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [21]:
scaled_inputs = Absenteeism_scaler.transform(unscaled_inputs)

In [22]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
0           0         0         0         1  0.182726                1.005844   
1           0         0         0         0  0.182726               -1.574681   
2           0         0         0         1  0.182726               -0.654143   
3           1         0         0         0  0.182726                0.854936   
4           0         0         0         1  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695         1         0         0         0 -0.388293               -0.654143   
696         1         0         0         0 -0.388293                0.040034   
697         1         0         0         0 -0.388293                1.624567   
698         0         0         0         1 -0.388293                0.190942   
699         0         0         0         1 -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [23]:
scaled_inputs.shape

(700, 11)

### Split the data & shuffle

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train , x_test , y_train , y_test = train_test_split(scaled_inputs, Targets,
                                                       train_size =  0.8, shuffle=True, random_state = 20)

In [26]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [27]:
print(x_test.shape , y_test.shape)

(140, 11) (140,)


### Logistic Regression with sklearn

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train, y_train)

LogisticRegression()

In [31]:
reg.score(x_train, y_train) # 80% accuaracy 

0.7732142857142857

### Manually check the accuracy

In [32]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
len(model_outputs)

560

In [34]:
np.sum(model_outputs == y_train) / len(model_outputs)

0.7732142857142857

### Finding the Intercept and Coeffiencts

In [35]:
reg.intercept_

array([-1.6469898])

In [36]:
reg.coef_

array([[ 2.80000644,  0.95174778,  3.1140605 ,  0.83835931,  0.15897713,
         0.60513709, -0.16990589,  0.27998236, -0.21017416,  0.34842434,
        -0.27721907]])

In [37]:
feature_name = unscaled_inputs.columns.values

In [38]:
summary_table = pd.DataFrame (columns=['Feature name'], data=feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason_1     2.800006
1                 Reason_2     0.951748
2                 Reason_3     3.114061
3                 Reason_4     0.838359
4                    Month     0.158977
5   Transportation Expense     0.605137
6                      Age    -0.169906
7          Body Mass Index     0.279982
8                Education    -0.210174
9                 Children     0.348424
10                    Pets    -0.277219

In [39]:
summary_table.index = summary_table.index + 1

In [40]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.646990
1                 Reason_1     2.800006
2                 Reason_2     0.951748
3                 Reason_3     3.114061
4                 Reason_4     0.838359
5                    Month     0.158977
6   Transportation Expense     0.605137
7                      Age    -0.169906
8          Body Mass Index     0.279982
9                Education    -0.210174
10                Children     0.348424
11                    Pets    -0.277219

In [41]:
summary_table["Odds_Ratio"] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_Ratio
0                Intercept    -1.646990    0.192629
1                 Reason_1     2.800006   16.444753
2                 Reason_2     0.951748    2.590233
3                 Reason_3     3.114061   22.512270
4                 Reason_4     0.838359    2.312570
5                    Month     0.158977    1.172311
6   Transportation Expense     0.605137    1.831503
7                      Age    -0.169906    0.843744
8          Body Mass Index     0.279982    1.323106
9                Education    -0.210174    0.810443
10                Children     0.348424    1.416833
11                    Pets    -0.277219    0.757888

In [42]:
#Note:i=Inputs with Values for Coefficient around 0 & Values for Odds_Ratio around 1 are usually not important and can be removed
summary_table.sort_values('Odds_Ratio', ascending=False)

Feature name  Coefficient  Odds_Ratio
3                 Reason_3     3.114061   22.512270
1                 Reason_1     2.800006   16.444753
2                 Reason_2     0.951748    2.590233
4                 Reason_4     0.838359    2.312570
6   Transportation Expense     0.605137    1.831503
10                Children     0.348424    1.416833
8          Body Mass Index     0.279982    1.323106
5                    Month     0.158977    1.172311
7                      Age    -0.169906    0.843744
9                Education    -0.210174    0.810443
11                    Pets    -0.277219    0.757888
0                Intercept    -1.646990    0.192629

### Testing the model

In [43]:
reg.score(x_test, y_test)

0.75

In [44]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71342516, 0.28657484],
       [0.5873216 , 0.4126784 ],
       [0.44016153, 0.55983847],
       [0.78163061, 0.21836939],
       [0.08407928, 0.91592072],
       [0.3348226 , 0.6651774 ],
       [0.29971206, 0.70028794],
       [0.13112385, 0.86887615],
       [0.78627908, 0.21372092],
       [0.74906578, 0.25093422],
       [0.49395555, 0.50604445],
       [0.22492002, 0.77507998],
       [0.07135527, 0.92864473],
       [0.73173354, 0.26826646],
       [0.30957854, 0.69042146],
       [0.54726422, 0.45273578],
       [0.55051921, 0.44948079],
       [0.53926379, 0.46073621],
       [0.40197149, 0.59802851],
       [0.05365482, 0.94634518],
       [0.70030387, 0.29969613],
       [0.78163061, 0.21836939],
       [0.42028246, 0.57971754],
       [0.42028246, 0.57971754],
       [0.24801464, 0.75198536],
       [0.74567806, 0.25432194],
       [0.51026557, 0.48973443],
       [0.8569309 , 0.1430691 ],
       [0.20365204, 0.79634796],
       [0.78163061, 0.21836939],
       [0.

In [45]:
predicted_proba.shape

(140, 2)

In [46]:
predicted_proba[:,1]

array([0.28657484, 0.4126784 , 0.55983847, 0.21836939, 0.91592072,
       0.6651774 , 0.70028794, 0.86887615, 0.21372092, 0.25093422,
       0.50604445, 0.77507998, 0.92864473, 0.26826646, 0.69042146,
       0.45273578, 0.44948079, 0.46073621, 0.59802851, 0.94634518,
       0.29969613, 0.21836939, 0.57971754, 0.57971754, 0.75198536,
       0.25432194, 0.48973443, 0.1430691 , 0.79634796, 0.21836939,
       0.36947677, 0.67913195, 0.68508325, 0.52870791, 0.21836939,
       0.53505228, 0.22144744, 0.73673169, 0.40500758, 0.60504297,
       0.21072119, 0.45227108, 0.23749326, 0.39847178, 0.82763577,
       0.56771922, 0.69120847, 0.28657484, 0.2192347 , 0.2032712 ,
       0.57634482, 0.32954238, 0.6651774 , 0.26937528, 0.83323682,
       0.43484145, 0.88365871, 0.23125087, 0.33433749, 0.34451397,
       0.69915101, 0.6549938 , 0.29244583, 0.79186052, 0.20752232,
       0.26838009, 0.08710411, 0.22144744, 0.73215219, 0.30536526,
       0.22144744, 0.2900789 , 0.90443841, 0.46065771, 0.60175

### Save the Model

In [47]:
import pickle

In [48]:
with open('Model', 'wb') as file:
    pickle.dump(reg, file)

In [49]:
with open('Scaler', 'wb') as file:
    pickle.dump(Absenteeism_scaler, file)